{{- define "extendeddaemonset.rbacRules" }}
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - get
    - watch
- apiGroups:
    - "apps"
  resources:
    - daemonset
  verbs:
    - get
    - watch
    - list
- apiGroups:
    - datadoghq.com
  resources:
    - 'extendeddaemonsets'
    - 'extendeddaemonsets/status'
    - 'extendeddaemonsetreplicasets'
    - 'extendeddaemonsetreplicasets/status'
    - 'extendeddaemonsetsettings'
    - 'extendeddaemonsetsettings/status'
  verbs:
    - '*'
{{- end }}