{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "extendeddaemonset.fullname" . }}
  labels:
{{ include "extendeddaemonset.labels" . | indent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - create
- apiGroups:
    - ""
  resources:
    - configmaps
  resourceNames:
    - extendeddaemonset-lock
  verbs:
    - update
    - get
    - watch
{{- if not .Values.clusterScope }}
{{- include "extendeddaemonset.rbacRules" . }}
{{- end }}
{{- end -}}
